'use client';

import { useCallback, useEffect, useMemo, useState, useTransition } from 'react';

import type { Role } from '@/features/auth';
import { Button } from '@/components/ui/button';

import { listActivityPage } from '../activityService';
import type { ActivityListParams } from '../types';
import type { ActivityLog } from '../types';
import { ActivityTimeline } from './ActivityTimeline';
import { isAdmin } from '@/lib/rbac';
import { supabase } from '@/lib/supabaseClient';

const PAGE_SIZE = 28;

interface UserChip {
  id:   string;
  name: string;
}

interface ActivityPageClientProps {
  role:           Role;
  currentUserId:  string;
  initialSearch?: string;
}

export function ActivityPageClient({
  role,
  currentUserId,
  initialSearch,
}: ActivityPageClientProps) {
  const [entries, setEntries]       = useState<ActivityLog[]>([]);
  const [total, setTotal]           = useState(0);
  const [page, setPage]             = useState(1);
  const [pending, startRefresh]      = useTransition();
  const [userOptions, setUserOptions] = useState<UserChip[]>([]);

  const [filters, setFilters] = useState<Omit<ActivityListParams, 'page' | 'pageSize'>>({
    query: initialSearch ?? '',
    userId: null,
    actionType: '',
    entityType: '',
    entityId: '',
    createdFromIso: '',
    createdToIso: '',
  });

  const admin = isAdmin(role);

  useEffect(() => {
    void (async () => {
      const { data } = await supabase
        .from('users')
        .select('id,name,email')
        .order('name', { ascending: true });
      const list: UserChip[] = (data ?? []).map((u) => ({
        id: u.id,
        name: u.name?.trim() || u.email?.split('@')[0] || u.id.slice(0, 8),
      }));
      setUserOptions(list);
    })();
  }, []);

  const params = useMemo(
    (): ActivityListParams => ({
      page,
      pageSize: PAGE_SIZE,
      query:          filters.query?.trim() || undefined,
      userId:         filters.userId || undefined,
      actionType:     filters.actionType?.trim() || undefined,
      entityType:     filters.entityType?.trim() || undefined,
      entityId:       filters.entityId?.trim() || undefined,
      createdFromIso: filters.createdFromIso || undefined,
      createdToIso:   filters.createdToIso || undefined,
    }),
    [page, filters],
  );

  const fetchPage = useCallback(() => {
    startRefresh(() => {
      void (async () => {
        try {
          const { entries: rows, total: t } = await listActivityPage(params);
          setEntries(rows);
          setTotal(t);
        } catch (e) {
          console.error('[activity] list failed', e);
          setEntries([]);
        }
      })();
    });
  }, [params]);

  useEffect(() => {
    fetchPage();
  }, [fetchPage]);

  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));

  return (
    <div className="mx-auto max-w-5xl space-y-6 px-4 py-6 md:px-6">
      <header className="space-y-1">
        <h1 className="text-2xl font-semibold tracking-tight text-gray-900">Activity</h1>
        <p className="text-sm text-gray-500">
          Immutable audit trail — generated by the database when posts, media, and roles change.
        </p>
      </header>

      <section className="rounded-xl border border-gray-100 bg-white p-4 shadow-sm ring-1 ring-black/[0.02]">
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <label className="flex flex-col gap-1 text-xs font-semibold text-gray-500">
            Search
            <input
              className="h-10 rounded-lg border border-gray-200 px-3 text-sm"
              placeholder="Message or action keyword"
              value={filters.query ?? ''}
              onChange={(e) => {
                setPage(1);
                setFilters((f) => ({ ...f, query: e.target.value }));
              }}
            />
          </label>

          <label className="flex flex-col gap-1 text-xs font-semibold text-gray-500">
            Actor
            <select
              className="h-10 rounded-lg border border-gray-200 bg-white px-3 text-sm"
              value={filters.userId ?? ''}
              onChange={(e) => {
                setPage(1);
                setFilters((f) => ({
                  ...f,
                  userId: e.target.value || null,
                }));
              }}
            >
              <option value="">Everyone</option>
              {(admin
                ? userOptions
                : userOptions.filter((u) => u.id === currentUserId)
              ).map((u) => (
                <option key={u.id} value={u.id}>
                  {u.name}
                </option>
              ))}
            </select>
          </label>
          <label className="flex flex-col gap-1 text-xs font-semibold text-gray-500">
            Action contains
            <input
              className="h-10 rounded-lg border border-gray-200 px-3 text-sm"
              placeholder="e.g. publishing.retry"
              value={filters.actionType ?? ''}
              onChange={(e) => {
                setPage(1);
                setFilters((f) => ({ ...f, actionType: e.target.value }));
              }}
            />
          </label>

          <label className="flex flex-col gap-1 text-xs font-semibold text-gray-500">
            Entity type
            <select
              className="h-10 rounded-lg border border-gray-200 bg-white px-3 text-sm"
              value={filters.entityType ?? ''}
              onChange={(e) => {
                setPage(1);
                setFilters((f) => ({ ...f, entityType: e.target.value }));
              }}
            >
              <option value="">Any</option>
              <option value="post">post</option>
              <option value="media">media</option>
              <option value="post_platform">post_platform</option>
              <option value="user">user</option>
            </select>
          </label>

          <label className="flex flex-col gap-1 text-xs font-semibold text-gray-500">
            Entity UUID (post / user …)
            <input
              className="h-10 rounded-lg border border-gray-200 px-3 font-mono text-xs"
              placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
              value={filters.entityId ?? ''}
              onChange={(e) => {
                setPage(1);
                setFilters((f) => ({ ...f, entityId: e.target.value }));
              }}
            />
          </label>

          <label className="flex flex-col gap-1 text-xs font-semibold text-gray-500">
            From (UTC date)
            <input
              type="date"
              className="h-10 rounded-lg border border-gray-200 px-3 text-sm"
              value={(filters.createdFromIso ?? '').slice(0, 10)}
              onChange={(e) => {
                setPage(1);
                const v = e.target.value;
                setFilters((f) => ({
                  ...f,
                  createdFromIso: v ? new Date(`${v}T00:00:00.000Z`).toISOString() : '',
                }));
              }}
            />
          </label>

          <label className="flex flex-col gap-1 text-xs font-semibold text-gray-500">
            To (UTC date)
            <input
              type="date"
              className="h-10 rounded-lg border border-gray-200 px-3 text-sm"
              value={(filters.createdToIso ?? '').slice(0, 10)}
              onChange={(e) => {
                setPage(1);
                const v = e.target.value;
                setFilters((f) => ({
                  ...f,
                  createdToIso: v ? new Date(`${v}T23:59:59.999Z`).toISOString() : '',
                }));
              }}
            />
          </label>

        </div>

        <div className="mt-4 flex flex-wrap items-center gap-2">
          <Button type="button" variant="outline" size="sm" disabled={pending} onClick={() => fetchPage()}>
            Refresh
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={() => {
              setFilters({
                query:          '',
                userId:         null,
                actionType:     '',
                entityType:     '',
                entityId:       '',
                createdFromIso: '',
                createdToIso:   '',
              });
              setPage(1);
            }}
          >
            Clear filters
          </Button>
          <span className="ml-auto text-xs text-gray-500">
            Showing {entries.length} rows on this page · {total} total matches
          </span>
        </div>
      </section>

      {pending && entries.length === 0 ? (
        <div className="space-y-3">
          {Array.from({ length: 5 }).map((_, i) => (
            <div key={i} className="h-24 animate-pulse rounded-xl bg-gray-100" />
          ))}
        </div>
      ) : (
        <ActivityTimeline entries={entries} />
      )}

      <div className="flex justify-between gap-2 border-t border-gray-100 pt-4">
        <Button
          type="button"
          variant="outline"
          disabled={page <= 1 || pending}
          onClick={() => setPage((p) => Math.max(1, p - 1))}
        >
          Previous
        </Button>
        <p className="self-center text-xs text-gray-500">
          Page {page} / {totalPages}
        </p>
        <Button
          type="button"
          variant="outline"
          disabled={page >= totalPages || pending}
          onClick={() => setPage((p) => p + 1)}
        >
          Next
        </Button>
      </div>
    </div>
  );
}
